// This took forever!!
var categories = [
    "Biscuits",
    "Cheese",
    "Ice Cream",
    "Waffles",
    "Frozen Fruit",
    "Whipped Topping",
    "Frozen Novelties",
    "Frozen Breakfast",
    "Orange Juice",
    "Milk",
    "Cream",
    "Frozen Meals (Single)",
    "Frozen Meals (Lite)",
    "Frozen Meals (Family)",
    "Frozen Meals (Vegetarian)",
    "Bread (Frozen)",
    "Vegatables (Frozen)",
    "International Frozen Foods",
    "Chicken (Frozen)",
    "Beef (Frozen)",
    "Seafood (Frozen)",
    "Potatoes (Frozen)",
    "Frozen Snacks",
    "Pizza",
    "Pizza (Single)",
    "Car Accessories",
    "Air Filters",
    "Lightbulbs",
    "Office Supplies",
    "Pet Treats",
    "Litter",
    "Cat Food (Wet)",
    "Cat Food (Dry)",
    "Dog Food (Wet)",
    "Dog Food (Dry)",
    "Bird Food",
    "Small Animal Food",
    "Charcoal",
    "Toilet Paper",
    "Party Supplies",
    "Food Storage",
    "Storage Bags",
    "Trash Bags",
    "Paper Towels",
    "Cleaning Supplies",
    "Swiffers",
    "Mops",
    "Sponges",
    "Dish Care",
    "Bleach",
    "Fabric Softener",
    "Detergent",
    "Air Freshener",
    "Insect Repellent",
    "Soda/Soft Drinks",
    "Bread",
    "Energy Drinks",
    "Water",
    "Buns/Bagels",
    "Snack Cakes",
    "Juices",
    "Sports Drinks",
    "Family Snacks",
    "Jam/Jelly",
    "Peanut Butter",
    "Pancake Mix",
    "Syrup",
    "Breakfast Bars",
    "Cereal",
    "Crackers",
    "Cookies",
    "Candy",
    "Potato Chips",
    "Popcorn",
    "Baby Toys",
    "Baby Wipes",
    "Diapers",
    "Coffee",
    "Coffee Filters",
    "Tea",
    "Hot Cocca",
    "Baby Food/Formula",
    "Condiments",
    "Pickles",
    "Spices",
    "Flour",
    "Disposable Baking Ware",
    "Vinegar",
    "Oil",
    "Cake Mix",
    "Gelatin/Jello (Dry)",
    "Icing",
    "Sweet Toppings",
    "Baking Soda",
    "Sugar",
    "Salad Dressing",
    "European Foods",
    "Mediterranean Foods",
    "Asian Foods",
    "Latin American Foods",
    "Pasta (Canned)",
    "Pasta (Dry)",
    "Pasta Sauce",
    "Tuna",
    "Soup (Canned)",
    "Soup (Dry)",
    "Rice",
    "Beans",
    "Potatoes (Instant)",
    "Gravy",
    "Pizza Crust",
    "Vegatables (Canned)",
    "Tomatoes (Canned)",
    "Fruit (Canned)",
    "Mac n' Cheese",
    "Seasonal Items",
    "Kitchen Ware",
    "Greeting Cards",
    "Coffee Makers",
    "Plates (Glass)",
    "Crock Pots",
    "Cups (Glass)",
    "Jugs (Glass)",
    "Toasters",
    "Utensils (Metal)",
    "Rags/Towels",
    "Food Processors",
    "Blenders",
    "Pyrex (Glass Bakeware)",
    "Books",
    "Sunglasses",
    "Pots and Pans",
    "Magazines",
    "Potato Chips (Organic)",
    "Nuts (Organic)",
    "Energy Bars (Organic)",
    "Drinks (Organic)",
    "Soda/Soft Drinks (Organic)",
    "Coffee (Organic)",
    "Soup (Organic)",
    "Sauces (Organic)",
    "Juices (Organic)",
    "Beauty (Natural)",
    "Wheat/Gluten-Free Foods",
    "Cookies (Organic)",
    "Crackers (Organic)",
    "Chocolate (Organic)",
    "Cereal (Organic)",
    "Frozen Foods (Organic)",
    "Milk (Organic)",
    "Beer",
    "Fruit",
    "Apples",
    "Potatoes",
    "Onions",
    "Produce",
    "Salad Dressing (Cold)",
    "Cake",
    "Delicatessen",
    "Hot Meals",
    "Wine",
    "Cheese (Fancy)",
    "Spreads (Humus)",
    "Sushi",
    "Beef",
    "Chicken",
    "Meat (Fresh)",
    "Seafood (Fresh)",
    "Meat (Organic)",
    "Prepared Meats",
    "Sausage",
    "Lunch Meats",
    "Bacon",
    "Eggs",
    "Butter",
    "Yogurt",
    "Gelatin/Jello (Cold)",
    "Sour Cream",
    "Cotton Balls",
    "Nail Care",
    "Cosmetics",
    "Acne",
    "Face Care",
    "Sunscreen",
    "Hair Care",
    "Bubble Bath",
    "Lotion",
    "Soap",
    "Hand Sanitizer",
    "Shampoo",
    "Incontinence",
    "Adult Nutrition",
    "Pain Relief",
    "Fiber",
    "Laxitives",
    "Heartburn Medication",
    "First Aid",
    "Heat Wraps",
    "Eye Care",
    "Foot Care",
    "Travel-Sized Items",
    "Mouthwash",
    "Toothpaste",
    "Toothbrushes",
    "Styling Tools",
    "Hair Brushes",
    "Deodorant",
    "Hair Color",
    "Pharmacy",
    "Vitamins",
    "Family Planning",
    "Feminine Items",
    "Socks",
    "Protein Powder",
    "Shaving Cream",
    "Razors",
    "Cold/Flu Medication",
    "Lip Balm"
];

// Constructs the Bloodhound suggestion engine
var categories = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace("value"),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  local: $.map(categories, function(category) { return { value: category }; })
});
 
// Kicks off prefetching and loading/processing
categories.initialize();
 
$("#sm-category-text-entry").typeahead({
  hint: false,
  highlight: true,
  minLength: 1,
},
{
  name: "categories",
  displayKey: "value",
  source: categories.ttAdapter()
});